version: "3.9"
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sendix
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      # Igual a tu .env pero apuntando al servicio db
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/sendix?schema=public
      - PORT=4000
      - CORS_ORIGIN=http://localhost:4000
    ports:
      - "4000:4000"
    restart: unless-stopped
volumes:
  pgdata:
