services:
  - type: web
    name: sendix-web
    env: node
    plan: free
    buildCommand: npm ci && npm run build
  startCommand: npm run prisma:push && npm start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 4000
      - key: CORS_ORIGIN
        value: "*"
    healthCheckPath: /health
